version: "3.9"
services:
  backend:
    build: ./cody-backend
    ports:
      - "8767:8000"
    volumes:
      - maven:/../root/.m2/repository
  frontend:
    build: ./cody-client
    ports:
      - "8766:3000"
    volumes:
      - node:/usr/src/app/node_modules
      - ./cody-client:/usr/src/app
volumes:
  node:
  maven: